Notification when borrowing is created
pashawarganov/library-api pull request #8
Opened 2024-10-18 08:30 UTC by Sergi0bbb

2024-10-18 08:36 UTC, pashawarganov commented on borrowing/views.py
> +            message = f"New borrowing created: {borrowing["id"]}"
make more informative message like "id, book, expected return date"

2024-10-18 08:36 UTC, olena4reunited requested changes
Move all changes in file notification_when_borrowing_created.py to new file outside the apps with descriptive name telegram_bot.py

2024-10-18 08:36 UTC, yashkunn commented on borrowing/notification_when_borrowing_created.py
> +bot = Bot(token=TOKEN, default=DefaultBotProperties(parse_mode=ParseMode.HTML))
I recommend adding a check like
if not TOKEN or not CHAT_ID:
    ...

2024-10-18 08:38 UTC, pashawarganov commented on .env.sample
> +CHAT_ID=YOUR_TELEGRAM_CHAT_ID
add empty line in end of file

2024-10-18 08:39 UTC, pashawarganov requested changes
Make some changes

2024-10-18 10:43 UTC, ABaidin approved these changes

2024-10-19 10:29 UTC, panichqa approved these changes

2024-10-19 13:02 UTC, panichqa approved these changes

2024-10-19 13:08 UTC, yashkunn approved these changes

2024-10-19 13:14 UTC, yashkunn approved these changes

2024-10-19 13:35 UTC, yashkunn approved these changes

2024-10-19 13:36 UTC, ABaidin approved these changes

2024-10-19 13:36 UTC, olena4reunited approved these changes

2024-10-19 13:42 UTC, pashawarganov approved these changes

2024-10-19 13:43 UTC, merged